---
- name: rpm install postgresql repos
  package: name={{ rpmurl.redhat }}

- name: install postgresql
  yum: name={{ item }} state=latest
  with_items:
    - "{{ package_name }}-server"
    - "{{ package_name }}-devel"
    - "{{ package_name }}-contrib"
    - "{{ package_name }}-libs"
    - python-psycopg2

- name: postgres user sudores
  lineinfile: 
    dest: /etc/sudoers.d/postgres 
    owner: root
    group: root
    mode: 0440
    line: "%vagrant ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name: postgresql initdb
  shell: "/usr/pgsql-{{ version }}/bin/{{ package_name }}-setup initdb"

- name: start postgresql
  service: name="postgresql-{{ version }}" state=started  enabled=yes

- name : create database
  postgresql_db: 
    name: "{{ dbname }}"
    encoding: "UTF-8"
    login_user: postgres
  sudo_user: postgres
  sudo: yes

- name: create user
  postgresql_user: 
    db: "{{ dbname }}"
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    priv: ALL
    state: present
    login_user: postgres
  sudo_user: postgres
  sudo: yes
